env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  upgrade_provider:
    name: upgrade-provider
    runs-on: ubuntu-latest
    steps:
    - name: Call upgrade provider action
      uses: pulumi/pulumi-upgrade-provider-action@12996503de2aaddd72c7426efc43331a8970894f # v0.0.19
      with:
        kind: check-upstream-version

permissions:
  contents: write
  issues: write

name: Check upstream upgrade
on:
  workflow_dispatch: {} #so we can run this manually if necessary.
  schedule:
  # 3 AM UTC ~ 8 PM PDT / 7 PM PST daily. Time chosen to run during off hours.
  - cron: 0 3 * * *
